# nginx-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-deployment
  labels:
    app: auction
spec:
  replicas: 1  # 변경 가능: 원하는 파드 수
  selector:
    matchLabels:
      app: auction
  template:
    metadata:
      labels:
        app: auction
    spec:
      containers:
      - name: auction
        image: leeinhong9512/panda-backend:15948850ee4cf7dc89ccca748d049d4492ae4503
        ports:
        - containerPort: 8081  # Nginx가 사용하는 포트
        volumeMounts:
        - name: tz-seoul
          mountPath: /etc/localtime
      volumes:
      - name: tz-seoul
        hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
        



---

# nginx-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: auction-service
spec:
  selector:
    app: auction
  ports:
    - protocol: TCP
      port: 8081  # 서비스에 노출되는 포트
      targetPort: 8081  # 파드에 포워딩되는 포트
      nodePort: 31000  # 변경 가능: 노드 포트 번호 (30000 ~ 32767 사이의 값을 선택)
  type: NodePort  # 서비스 유형을 NodePort로 변경
  
