# nginx-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aution-deployment
  labels:
    app: aution
spec:
  replicas: 1  # 변경 가능: 원하는 파드 수
  selector:
    matchLabels:
      app: aution
  template:
    metadata:
      labels:
        app: aution
    spec:
      containers:
      - name: aution
        image: leeinhong9512/panda-backend:1936a82e24d17051f1212606dc09f28dcddc2e30
        ports:
        - containerPort: 8081  # Nginx가 사용하는 포트



---

# nginx-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: aution-service
spec:
  selector:
    app: aution
  ports:
    - protocol: TCP
      port: 8081  # 서비스에 노출되는 포트
      targetPort: 8081  # 파드에 포워딩되는 포트
      nodePort: 31000  # 변경 가능: 노드 포트 번호 (30000 ~ 32767 사이의 값을 선택)
  type: NodePort  # 서비스 유형을 NodePort로 변경
  
